name: deploy

on: push

jobs:
  my-app:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build application
        run: |
          mvn clean install
      - name: Upload applicationbuildp
        uses: appleboy/scp-action@master
        with:       
          host: ${{ secrets.SERVER_IP_ADDRESS }}        
          username: ${{ secrets.SERVER_USERNAME }}      
          password: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "target/my-app-1.0-SNAPSHOT.jar"      
          target: "~/source"
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}       
          username: ${{ secrets.SERVER_USERNAME }}     
          password: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            /etc/init.d/my-app stop
            mkdir ~/source/deploy
            mv ~/source/my-app-1.0-SNAPSHOT.jar ~/deploy/my-app.jar
            rm -rf /etc/init.d/my-app
            ln -s -f ~/deploy/my-app.jar /etc/init.d/my-app
            /etc/init.d/my-app start